Martins
AdoptOpenJDK/openjdk-website pull request #973
Opened 2021-04-19 14:21 UTC by Martins-O-U

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

2021-04-19 16:11 UTC, smlambert reviewed
First review comments, @Martins-O-U can you update the PR title to something more meaningful like "Update Debian/Ubuntu instruction" and can you update the description to include a "Fixes #960" statement so that when the PR will be merged it will automatically close the github issue?

2021-04-23 23:58 UTC, Martins-O-U commented
Hello @smlambert, can this Pull Request be given a second look after the title update?

2021-04-28 15:42 UTC, karianna commented
@Martins-O-U it's a bit hard to see the change due to all of the whitespace changes.  Did you apply some sort of a formatter?  If it's possible to redo this PR without those changes would be preferable...

2021-04-28 15:44 UTC, karianna requested changes
it's a bit hard to see the change due to all of the whitespace changes. Did you apply some sort of a formatter? If it's possible to redo this PR without those changes would be preferable...

2021-04-28 15:44 UTC, karianna commented on src/handlebars/installation.handlebars
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/styles/obsidian.min.css">' }}
should stay on one line

2021-04-28 22:34 UTC, Martins-O-U commented
Hello @karianna and @smlambert,
I am sorry my code formatter was on when I worked on the task, thus it formatted some of the lines. It has now been fixed.  
On this PR, you would still see the lines where the formatting was removed displaying as effected changes. However, the section with actual edits requiring review is between line 339 - 465 (Debian/Ubuntu and its distributions installation)

Please, would you be able to review based on lines 339 - 465, or will it be better if I close this PR and make an entirely new PR?

2021-04-29 14:59 UTC, karianna commented
If you could make a new PR that would help (small whitespace changes we can live with, but some of the changes have wrapped lines etc)

2021-04-29 21:33 UTC, closed without merging